name: Build & Release

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build & Make (Windows)
        run: npm run make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/make/**/*
          retention-days: 5
